### ISSUE TITLE
[Ayudantía 3] Visualizar los archivos de frontend en navegador

### ISSUE THREAD

**Issue by gsalinas0** [IIC2513-2022-2/syllabus#1]
Hola.

No pude asistir a la ayudantía 3 del jueves pasado, por lo que ví las cápsulas y el código subido para ponerme al día. Sin embargo, no logro entender para que se ocupan los archivos en la carpeta de frontend, ya que no se menciona nada de esto en las cápsulas y en los archivos de backend no veo nada que establezca alguna "conexión" entre ambas partes.

Corrí en el navegador el HTML con Live Server. Sin embargo, no veo como es que este se conecta con el backend. En las cápsulas no se menciona nada y no estoy seguro de como seguir o poder hacer la conexión. ¿Que debo hacer?

Saludos

**Comment by Mamunoz42** [comment]
Hola @Gsalinas1506!

En primer lugar espero estes teniendo un buen inicio de semana 🤩.

Respecto a tu pregunta, en el archivo `índex.js` se realiza la conexión con el backend haciendo uso de `fetch()`. Para hacer uso del fetch debes tener ojo 👁️ con siempre entregarle el método a través el cual te comunicaras con el backend, en el ejemplo se utiliza **GET**. 

Es importante notar que al final el backend y frontend son dos programas independientes que se comunican a través de los métodos HTTP.

Por último, para ver que la conexión se llevo a cabo exitosamente debes revisar la **consola del servidor**, lugar en el cual verás la request que realiza el frontend. Puedes agregar `console.log()` en la función creada en backend que recibe la request para que puedas ver si te funciona y de que forma funciona.

Mucho éxito con el estudio para la interrogación 😄
