### ISSUE TITLE
[I1 S1] Problema con servidor local

### ISSUE THREAD

**Issue by sperezmasri** [IIC2513-2022-2/syllabus#10]
Al correr mi app localmente en el puerto 3000 **sí** puedo acceder a través de ```http://localhost:3000/``` pero **no** puedo acceder a través de ```http://127.0.0.1:3000```. Es un problema si lo dejo así  o está bien igual? En caso de que no esté bien, como podría solucionarlo 🤔

**Comment by valeeeriquelme** [comment]
No vale la pena porque va a depender de quién lo revise. Si funciona con localhost, todo ok
