### ISSUE TITLE
Inputs [I1/S2]

### ISSUE THREAD

**Issue by kunafuego** [IIC2513-2022-2/syllabus#13]
Hola! Tengo una duda. En el enunciado dice que los valores de los mozos, baños, m2 del local y venta total diaria deben ser inputs que estén con el atributo disabled activado. Mi pregunta es, ¿pueden no ser inputs sino que otro tipo de dato? 

En ningún momento vamos a tener que ingresar valores a estos tags, por lo que no veo la razón para hacerlos inputs.

Muchas gracias,

Domingo

**Comment by HernanCabrera** [comment]
Hola, buen día
La idea es que sean inputs y manejen así el disabled. Esto es parte de un buen diseño, el día de mañana se require que alguien pueda ingresar información y habría que cambiar la estructura. Es por ende razonable que sean inputs
