### ISSUE TITLE
Cambiar estilo de Opción Orquesta/Bodega al Ver Anterior [I1/S2]

### ISSUE THREAD

**Issue by nicoabarca** [IIC2513-2022-2/syllabus#14]
Hola 👋🏼 , en caso de que para un cálculo anterior se haya marcado la opción orquesta o bodega, es necesario que al apretar Ver anterior se muestre el estilo correspondiente al estado en el cual estaba antes?
Gracias 😄

**Comment by HernanCabrera** [comment]
Es un deseable pues así se entiende mejor la razón de los cálculos.
Sin embargo dado que no se solicitó explícitamente, pueden omitir el cambio de estilos
