### ISSUE TITLE
[I1 S2] Ver anterior

### ISSUE THREAD

**Issue by agustinbc7** [IIC2513-2022-2/syllabus#17]
Hola, al apretar ver anterior, ¿los valores que se cambian son solo del total de venta, o también afecta al resto de los valores?

**Comment by HernanCabrera** [comment]
Son todos los valores que deben cambiar, asi se puede comprender el contexto del total mostrado en pantalla
Saludos

**Comment by ElTioAndresCabezas** [comment]
Con respecto a esto, es necesario cambiar los valores de input a los anteriores? (Me refiero a colocar la cantidad de mesas especificada anteriormente, además de la rotación y ocupación previa)
