### ISSUE TITLE
[I2 S2] Disabled inputs

### ISSUE THREAD

**Issue by agucova** [IIC2513-2022-2/syllabus#18]
En reglas mencionan como ejemplo:
```javascript
document.getElementById("inputX").disabled = true;
```
para deshabilitar un input.

¿Está bien si usamos el atributo `disabled` directamente? Suena como mala UX tener que esperar a que el JS cargue para que los inputs se muestren correctamente, y el atributo si es semántico.

**Comment by HernanCabrera** [comment]
OJO, el DOM tiene disable pero también los inputs tienen la propiedad disable, en ese caso y como bien lo menciona, es mucho mejor usar directamente el atributo del input
