### ISSUE TITLE
[I2 S2] Opciones orquesta, bodega

### ISSUE THREAD

**Issue by agucova** [IIC2513-2022-2/syllabus#19]
En el caso de las opciones de orquesta y bodega, ¿Podemos usar checkboxes (`type="checkbox"`) para representar esta clase de inputs? O debemos crear un botón para emular este comportamiento?

**Comment by HernanCabrera** [comment]
La idea era usar botones.
Si quiere usar checkboxes pude usarlos pero el diseño de la pantalla tiene que ser como el mostrado incluidos los estilos, en su caso, al marcar o desmarcar el checkbox.
