### ISSUE TITLE
[I1 S2] Mala practica

### ISSUE THREAD

**Issue by Yerko-Contreras** [IIC2513-2022-2/syllabus#20]
Hola buenas, el uso de max y min directamente en el html, como parametros de input se considera mala practica?

**Comment by HernanCabrera** [comment]
En realidad no entiendo el contexto al que se refiere, sin embargo, para aclarar, cualquier programación inline es considerado mala práctica.
Si lo que tiene en mente no es nada inline y es algo propio de HTML relacionado con la estructura de su página, entonces no lo sería.

**Comment by tamyhan** [comment]
Hola! Tengo la misma duda y no me queda claro. Cuándo el input es de tipo "number", se pueden usar los atributos max, min y step ?
