### ISSUE TITLE
Duda con respecto a biblioteca

### ISSUE THREAD

**Issue by felipehen** [IIC2513-2022-2/syllabus#21]
Hola! queria saber si se pueden usar librerias en javascript. Se que no se pueden usar bibliotecas, pero la verdad, no se cual es la diferencia entre ambos terminos. Muchas gracias!

**Comment by HernanCabrera** [comment]
librería y biblioteca es lo mismo :-) en rigor library es el término en inglés que se traduce, muy mal, al español como "librería". 
Lo que se puede o no usar está en el propio enunciado. En general casi nada (flexbox y grid si se puede) y si conoce JQuery puede usarlo, pero el resto, en general No (React, Vue, Angular, etc. aunque a decir verdad cualquiera de estos lo encontraría excesivo para lo sencilla que es la pantalla de front)
