### ISSUE TITLE
[I1 S1] Problema al reconocer document en js

### ISSUE THREAD

**Issue by antoniablanco** [IIC2513-2022-2/syllabus#4]
Hola, no estoy segura si es que se puede preguntar. Pero mi archivo js dice no reconocer document, y lo tengo conectado en el html. con el mismo nombre, siendo que el css si me funciona.

**Comment by valeeeriquelme** [comment]
Tal vez intenta revisar si te falta algún / o cierre de tag. Hay páginas que te permiten revisar si está bien tu código. 

Más que eso no puedo ayudarte porque es parte de lo que se evalúa poder hacer la conexión. Espero que lo puedas solucionar.
