### ISSUE TITLE
[I1 S1] No inline en HTML

### ISSUE THREAD

**Issue by robertodea** [IIC2513-2022-2/syllabus#6]
Hola, sale en el enunciado que no se puede usar inline en el html. Esto significa que no se debe usar en ningún archivo incluyendo el CSS? Muchas gracias!

**Comment by valeeeriquelme** [comment]
Hola, al inline al que nos referimos es que no puede haber estilo dentro de un elemento HTML. No entiendo a que te refieres con que no pueda haber en el css.

**Comment by robertodea** [comment]
Eso significa por ejemplo que no podria dejar seteado los color iniciales de los botones desde el archivo HTML? Es que en el archivo css tengo el display como inline para los botones entonces por eso venia la pregunta.

**Comment by valeeeriquelme** [comment]
No puedes setear los colores en el archivo HTML. El display Inline no es lo mismo que Inline Style y que tengas el display seteado en el css no debería ser limitante para no poder setear también los colores.
