### ISSUE TITLE
[I1 S1] Dudas

### ISSUE THREAD

**Issue by mhrobles** [IIC2513-2022-2/syllabus#7]
Tengo algunas dudas respecto a los valores por default. Si no ingreso insumos, estos se mantienen como cero, pero hay un problema si el cero se ve en el input deshabilitado? o directamente no debe verse nada? por otro lado, si agrego personas, al momento de presionar en alguno de los botones de insumos, el input de cantidad de personas debe deshabilitarse? o se puede seguir cambiando este valor? pregunto porque si no se deshabilita, una persona podría poner insumos pero a ultimo momento cambiar las personas a cero, pero por el contrario, si deshabilito el cambiar la cantidad de personas, si me arrepiento de la cantidad de personas invitadas, no se podría cambiar. Y por otro lado, tengo que crear un insumo para las personas veganas? o simplemente asumo que cada persona vegana tendrá un costo asignado?

**Comment by valeeeriquelme** [comment]
1) No hay problema con que se vea el cero
2) Puedes dejar un supuesto indicando porque elegiste cierta forma de implementarlo 
3) Si entendí bien lo último en relación al insumo de la persona vegana, se indica en el enunciado como manejar esto

**Comment by valeeeriquelme** [comment]
En relación al punto 2, abordalo como parte de las validaciones que hay que implementar.

**Comment by mhrobles** [comment]
se me permite agregar un botón extra? o solo debo usar los que se especifican?

**Comment by valeeeriquelme** [comment]
@mhrobles no es necesario pero si puedes, importante denuevo indicar en el readme porque estimaste necesario agregarlo.

**Comment by mhrobles** [comment]
respecto a lo de personas veganas, sigo sin entender la regla, porque no se si tengo que asumir que por ejemplo, por persona vegana son 3000 pesos, o si tengo que agregar un insumo de verduras o algo asi 
![image](https://user-images.githubusercontent.com/37165583/190488007-2a38c020-76f3-416f-8ec1-aa2b3a9dd4e7.png)

**Comment by valeeeriquelme** [comment]
@mhrobles lo primero, solo manejas un precio y cantidad de personas. En el ejemplo que está en una nota al pie se explica mejor como sería el cálculo.

**Comment by mhrobles** [comment]
Mi ultima duda es, en el footer solo debo poner mi nombre y numero de alumno?

**Comment by valeeeriquelme** [comment]
@mhrobles lo que sale en el mock up
