### ISSUE TITLE
[I1 S1] Duda validación

### ISSUE THREAD

**Issue by VicenteSaldana** [IIC2513-2022-2/syllabus#8]
El enunciado menciona que es necesario validar cuando corresponda. ¿Esto implica enviar algún tipo de mensaje al usuario?  ¿O simplemente con que por ejemplo al calcular habiendo 0 personas el resultado total sea 0 bastaría? No entiendo bien a lo que se refiere específicamente con validar.

Muchas gracias :)

**Comment by valeeeriquelme** [comment]
Para realizar el cálculo tienes que fijarte que los inputs y botones correspondientes tengan los valores/comportamiento que se requiere. Por ejemplo, no deberías poder calcular si la cantidad total de personas es cero (este es uno de los escenarios que hay que validar)

**Comment by morbeta1234** [comment]
@valeeeriquelme en relación a esto, despues de hacer la validación de que haya alguna persona ingresada y que alguna opción de comida esté presionada, es necesario que haya más de 0 en esa opción. Por ejemplo, ingreso 5 personas, presiono vacuno pero lo dejo en 0 y aprieto calcular, puedo expresar 0 como total o tengo que hacer una validación extra?

**Comment by valeeeriquelme** [comment]
@morbeta1234 como no está especificado, va a ser decisión tuya de diseño. Podría ser que cuando se aprete un botón parta altiro con un valor distinto de 0 o que si se permita que sea cero, pero que al tratar de calcular se indique que hay que completar ese campo.
